let nums =[10, 20, 30, 40, 50];
console.log(nums.length);
let names =["jyothi", "satya", "mouni", "raji"];
names.push("hema");
console.log(names);
let fruits =["apple", "banana", "cherry"];
fruits.unshift("grapes");
console.log(fruits);
let flowers =["jasmine","rose","lilly", "marygold"];
flowers.shift();
console.log(flowers);
let veg =["carrot","tomato","potato","onion","chilly"];
veg.pop();
console.log(veg);
let age = 40;
console.log(typeof (age));
let obj_data={name:"jyo",num:"988"};
console.log(obj_data["num"]);
let animals=["rabbit","dog","cat","pig","goat","hen"];
console.log(animals[3]);
